### ISSUE TITLE
Error in download

### ISSUE THREAD

**Issue by rph-tufail** [beast1hack/skillshare-1hack#1]
Facing issue executing Download cell
```
Traceback (most recent call last):
  File "/root/.skillshare-1hack/dl.py", line 50, in <module>
    main()
  File "/root/.skillshare-1hack/dl.py", line 11, in main
    dl.download_course_by_url(course_url)
  File "/root/.skillshare-1hack/skillshare.py", line 29, in download_course_by_url
    self.download_course_by_class_id(m.group(1))
  File "/root/.skillshare-1hack/skillshare.py", line 32, in download_course_by_class_id
    data = self.fetch_course_data_by_class_id(class_id=class_id)
  File "/root/.skillshare-1hack/skillshare.py", line 69, in fetch_course_data_by_class_id
    assert res.status_code == 200, 'Fetch error, code == {}'.format(res.status_code)
AssertionError: Fetch error, code == 403
```

**Comment by BenmouluodAd** [comment]
same problem

**Comment by xscotophilic** [comment]
+1

**Comment by Somoud** [comment]
I think this sript is Fu**ing DEAD.

**Comment by jhoelzymari** [comment]
+1

**Comment by piratesephiroth** [comment]
the account died, it was probably a 2 month trial
